// apps/config/ui/src/components/StatusBar.svelte
<script>
  import IconShield from "~icons/lucide/shield";
  import IconCheck from "~icons/lucide/check";
  import IconScrollText from "~icons/lucide/scroll-text";
  import IconRotateCw from "~icons/lucide/rotate-cw";
  import IconPower from "~icons/lucide/power";
  import IconPlay from "~icons/lucide/play";
  import { invoke } from "../lib/ipc.js";
  import { app, startCore, restartCore, quitCore, toast } from "../lib/state.svelte.js";
  import {
    applyTheme,
    loadPreference,
    nextTheme,
    savePreference,
    themeIcon,
    themeLabel,
  } from "../lib/theme.js";

  const running = $derived(app.status.running);
  let themePref = $state(loadPreference());

  function cycleTheme() {
    themePref = nextTheme(themePref);
    savePreference(themePref);
    applyTheme(themePref);
  }

  async function openLog() {
    try {
      await invoke("open_log_dir");
    } catch (err) {
      toast("打开日志失败：" + err, true);
    }
  }

  // 显示核心回报的真实监控状态（core_status.monitoring）。
  const monitoring = $derived(app.status.monitoring);
  const monitorText = $derived(
    app.monitorPending ? "切换中…" : monitoring ? "热键生效" : "热键暂停",
  );
  const monitorTitle = $derived(
    monitoring
      ? "核心正在监听热键与鼠标触发"
      : "核心已停止监听：录制热键或调整鼠标设置时自动暂停，避免误触发",
  );

  const statusText = $derived(
    running === null ? "检测中…" : running ? "核心运行中" : "核心未运行",
  );
  const statusClass = $derived(
    running === null ? "pending" : running ? "online" : "offline",
  );
</script>

<footer class="statusbar">
  <div class="left">
    <span class="status {statusClass}">
      {#if running && app.status.elevated}
        <IconShield width="10" height="10" class="shield-dot" />
      {:else}
        <i class="dot"></i>
      {/if}
      {statusText}
    </span>

    {#if running === false}
      <button
        class="act icon-only ok"
        onclick={() => startCore(false)}
        title="启动核心"
        aria-label="启动核心"
      >
        <IconPlay width="14" height="14" />
      </button>
      <button
        class="act icon-only blue"
        onclick={() => startCore(true)}
        title="管理员启动"
        aria-label="管理员启动"
      >
        <IconShield width="14" height="14" />
      </button>
    {:else if running}
      {#if !app.status.elevated}
        <button
          class="act icon-only blue"
          onclick={() => restartCore(true)}
          title="管理员身份重启"
          aria-label="管理员身份重启"
        >
          <IconShield width="14" height="14" />
        </button>
      {/if}
      <button
        class="act icon-only warn"
        onclick={() => restartCore(app.status.elevated)}
        title="重启核心"
        aria-label="重启核心"
      >
        <IconRotateCw width="14" height="14" />
      </button>
      <button class="act icon-only danger" onclick={quitCore} title="退出核心" aria-label="退出核心">
        <IconPower width="14" height="14" />
      </button>
    {/if}
  </div>

  <div class="right">
    <button class="act icon" onclick={openLog} title="打开日志目录" aria-label="打开日志目录">
      <IconScrollText width="14" height="14" />
    </button>

    <button class="act icon" onclick={cycleTheme} title={themeLabel(themePref)} aria-label={themeLabel(themePref)}>
      {themeIcon(themePref)}
    </button>

    {#if running}
      <span class="monitor" class:paused={!monitoring} title={monitorTitle}>
        <i class="dot"></i>
        {monitorText}
      </span>
    {/if}
    <span class="save" class:saving={app.saving}>
      {#if app.saving}保存中…{:else}<IconCheck width="12" height="12" /> 已保存{/if}
    </span>
  </div>
</footer>

<style>
  .statusbar {
    height: 30px;
    flex: none;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 0 12px;
    background: var(--surface);
    border-top: 1px solid var(--border);
    font-size: 12px;
  }
  .left,
  .right {
    display: flex;
    align-items: center;
    gap: 8px;
    min-width: 0;
  }

  .status {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    color: var(--muted);
    white-space: nowrap;
  }
  .dot {
    width: 7px;
    height: 7px;
    border-radius: 50%;
    background: var(--muted);
  }
  .shield-dot {
    color: var(--ok);
  }
  .status.online {
    color: var(--ok);
  }
  .status.online .dot {
    background: var(--ok);
  }
  .status.offline {
    color: var(--danger);
  }
  .status.offline .dot {
    background: var(--danger);
  }

  .act {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding: 3px 10px;
    border-radius: 5px;
    font-size: 12px;
    color: var(--text);
    border: 1px solid var(--border);
    background: var(--surface-2);
    transition: background 0.12s, border-color 0.12s, color 0.12s;
  }
  .act:hover {
    background: var(--hover);
    border-color: var(--accent);
  }

  .act.icon {
    padding: 3px;
    width: 24px;
    height: 22px;
    justify-content: center;
    color: var(--muted);
    position: relative;
  }
  .act.icon:hover {
    color: var(--text);
  }
  .act.icon.active {
    color: var(--accent);
    background: var(--hover);
    border-color: var(--accent);
  }

  .act.icon-only {
    padding: 2px;
    width: 24px;
    height: 22px;
    justify-content: center;
    border: 1px solid transparent;
  }
  .act.icon-only:hover {
    border-color: currentColor;
  }

  .act.ok {
    color: var(--ok);
  }
  .act.ok:hover {
    background: rgba(47, 158, 99, 0.1);
  }

  .act.blue {
    color: #3b82f6;
  }
  .act.blue:hover {
    background: rgba(59, 130, 246, 0.1);
  }

  .act.warn {
    color: var(--warn);
  }
  .act.warn:hover {
    background: rgba(217, 119, 6, 0.1);
  }

  .act.danger {
    color: var(--danger);
  }
  .act.danger:hover {
    background: rgba(229, 72, 77, 0.1);
  }

  .monitor {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    color: var(--muted);
    white-space: nowrap;
  }
  .monitor .dot {
    background: var(--ok);
  }
  .monitor.paused {
    color: var(--warn);
  }
  .monitor.paused .dot {
    background: var(--warn);
    animation: blink 1.2s ease-in-out infinite;
  }
  @keyframes blink {
    50% {
      opacity: 0.3;
    }
  }

  .save {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    color: var(--muted);
    white-space: nowrap;
  }
  .save.saving {
    color: var(--accent);
  }

  @media (max-width: 560px) {
    .save,
    .monitor {
      display: none;
    }
  }
</style>

// docs/.vitepress/theme/components/StatusBar.vue
<script setup>
// 忠实复刻配置界面底部状态栏（apps/config/ui/src/components/StatusBar.svelte）。
// 图标直接取自 Lucide（与应用同源），因此显示效果与实际界面完全一致。
import { computed } from 'vue'
import { Shield, Play, RotateCw, Power, ScrollText, Check } from 'lucide-vue-next'

const props = defineProps({
  // offline：核心未运行 / user：普通用户运行 / admin：管理员运行
  variant: { type: String, default: 'user' },
})

const running = computed(() => props.variant !== 'offline')
const elevated = computed(() => props.variant === 'admin')

const statusText = computed(() => (running.value ? '核心运行中' : '核心未运行'))
const statusClass = computed(() => (running.value ? 'online' : 'offline'))
</script>

<template>
  <footer class="sb-statusbar" :aria-label="`状态栏示例：${statusText}`">
    <div class="sb-left">
      <span class="sb-status" :class="statusClass">
        <Shield v-if="running && elevated" :size="10" :stroke-width="2" class="sb-shield-dot" />
        <i v-else class="sb-dot"></i>
        {{ statusText }}
      </span>

      <template v-if="!running">
        <button class="sb-act sb-icon-only sb-ok" title="启动核心" type="button">
          <Play :size="14" :stroke-width="2" />
        </button>
        <button class="sb-act sb-icon-only sb-blue" title="管理员启动" type="button">
          <Shield :size="14" :stroke-width="2" />
        </button>
      </template>
      <template v-else>
        <button v-if="!elevated" class="sb-act sb-icon-only sb-blue" title="管理员身份重启" type="button">
          <Shield :size="14" :stroke-width="2" />
        </button>
        <button class="sb-act sb-icon-only sb-warn" title="重启核心" type="button">
          <RotateCw :size="14" :stroke-width="2" />
        </button>
        <button class="sb-act sb-icon-only sb-danger" title="退出核心" type="button">
          <Power :size="14" :stroke-width="2" />
        </button>
      </template>
    </div>

    <div class="sb-right">
      <button class="sb-act sb-icon" title="打开日志目录" type="button">
        <ScrollText :size="14" :stroke-width="2" />
      </button>
      <button class="sb-act sb-icon" title="主题：跟随系统" type="button">◐</button>

      <span v-if="running" class="sb-monitor" title="核心正在监听热键与鼠标触发">
        <i class="sb-dot sb-dot-ok"></i>
        热键生效
      </span>
      <span class="sb-save">
        <Check :size="12" :stroke-width="2" /> 已保存
      </span>
    </div>
  </footer>
</template>

<style scoped>
/* 强调色取自应用状态栏（与主题无关，保持一致）；面板底色随文档主题走。 */
.sb-statusbar {
  --sb-ok: #2f9e63;
  --sb-warn: #d97706;
  --sb-danger: #e5484d;
  --sb-blue: #3b82f6;

  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  height: 34px;
  padding: 0 12px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  background: var(--vp-c-bg-soft);
  font-size: 12px;
  color: var(--vp-c-text-1);
  user-select: none;
}
.sb-left,
.sb-right {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}

.sb-status {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: var(--vp-c-text-2);
  white-space: nowrap;
}
.sb-status.online { color: var(--sb-ok); }
.sb-status.offline { color: var(--sb-danger); }

.sb-dot {
  width: 7px;
  height: 7px;
  border-radius: 50%;
  background: currentColor;
  display: inline-block;
}
.sb-dot-ok { background: var(--sb-ok); }
.sb-shield-dot { color: var(--sb-ok); }

.sb-act {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 3px 6px;
  border-radius: 5px;
  font-size: 12px;
  line-height: 1;
  color: var(--vp-c-text-1);
  border: 1px solid transparent;
  background: transparent;
  cursor: default;
}
.sb-icon {
  color: var(--vp-c-text-2);
  border-color: var(--vp-c-divider);
  background: var(--vp-c-bg);
}
.sb-ok { color: var(--sb-ok); }
.sb-blue { color: var(--sb-blue); }
.sb-warn { color: var(--sb-warn); }
.sb-danger { color: var(--sb-danger); }

.sb-monitor {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  color: var(--vp-c-text-2);
  white-space: nowrap;
}
.sb-save {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  color: var(--vp-c-text-2);
  white-space: nowrap;
}

@media (max-width: 560px) {
  .sb-save,
  .sb-monitor { display: none; }
}
</style>
